jwt:
  key: ${SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86000000

spring:
  application:
    name: bloggingPlatformBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/blogging_platform_backend
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true





